### ISSUE TITLE
Blank Page

### ISSUE THREAD

**Issue by drewpate** [mitxpro-dev/learnjs#37]
The GitHub Page is coming up blank.
When running locally it. Looks like there is an issue with the base url. Take a look at the vite.config.ts file and the base Route in App.tsx

**Comment by drewpate** [comment]
@HudsonGraeme I created a pull request with my fix. Hopefully this is all it needs, or there might be something else required.

**Comment by codeTrackLift** [comment]
Hey @HudsonGraeme @drewpate,

Did a little bit of troubleshooting on this issue and found the following:
- Made a simple `Vite` project using `TypeScript`, but without `SWC`, see [this repo](https://github.com/codeTrackLift/vite-test).
- Followed the steps in this [Vite doc](https://vitejs.dev/guide/static-deploy.html#github-pages) and was able to deploy to `gh-pages`, see [this deployed site](https://codetracklift.github.io/vite-test/).
- I tried the same workflow change with a copy of `Learn JS`, but I was having trouble getting the site to show (same issue as this repo)
  - See [this test repo](https://github.com/codeTrackLift/temp), same issue as `Learn JS`
  - See [this deployed link](https://codetracklift.github.io/temp/), just a white page.
- Not sure if this is due to using `SWC` in `LearnJS`?
- Thoughts on how we should move forward?

**Comment by HudsonGraeme** [comment]
Thanks for the troubleshooting @codeTrackLift, @drewpate let me know about a [SO thread](https://stackoverflow.com/questions/74518887/blank-page-when-deploying-a-react-app-to-github-pages-and-vite) on the topic and there was a note in there about `basename` in `<BrowserRouter/>`

I suspect because we're using react-router-dom, the router is not basing it's main route off of `/learnjs` but instead `/` and as a result doesn't serve a page at any of the known routes. I made a change to my fork [here](https://github.com/HudsonGraeme/learnjs) and the site is [deployed](https://hudsongraeme.github.io/learnjs) and working as expected... I'll open a PR here for the same change and start praying this is the fix :joy:

**Comment by HudsonGraeme** [comment]
Success!
https://mitxpro-dev.github.io/learnjs/

**Comment by codeTrackLift** [comment]
@HudsonGraeme awesome! 🤩

**Comment by drewpate** [comment]
🤩 excellent work guys! @HudsonGraeme @codeTrackLift
